# //create database sample SQL
# CREATE DATABASE `zhirenhr` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 10
  host: xtscore.com
  username: root
  password: baichi

development:
  <<: *default
  database: soccer

test:
  <<: *default
  database: soccer

production:
  <<: *default
  database: soccer